blank_issues_enabled: true
contact_links:
  - name: Questions & Discussions
    url: https://github.com/alexanderpaolini/chat-summarize/discussions
    about: Ask questions and discuss ideas with the community
